version: '3.8'
services:
    php8_web:
        build: 
            context: .
        #image: php:8-apache
        container_name: php8_web
        #build: 
        #    context: .
        volumes:
            #- ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/php/:/usr/local/etc/php/conf.d
            - ./www:/var/www/html/:ro
            #- ./log/apache:/var/log/apache2
        links:
            - "php8_db:database"
        ports:
            - '60000:80'

    php8_db:
        image: postgres:latest
        container_name: php8_db
        restart: always
        environment:
            POSTGRES_PASSWORD: root
        #volumes:
        #    - ./log/mysql:/var/log/mysql/
        ports:
            - 60001:5432
